version: "3.8"
services:
  tourthecity-mysqldb:
    container_name: "tourthecity-mysqldb"
    image: mysql
    volumes:
      - /db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: tourthecitydb
      MYSQL_ROOT_PASSWORD: A4q9VOAFwXIAB2nO8U9ofjlbyyR9ysNzHWEI87zJfWct1ENhCS

  tourthecity-frontend:
    container_name: "tourthecity-frontend"
    image: tourthecity-frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
        - "./frontend:/frontend"
    ports:
      - "3000:3000"

  tourthecity-backend:
    container_name: "tourthecity-backend"
    image: tourthecity-backend
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
#    working_dir: /backend
    volumes:
          - "./backend:/backend"
    depends_on:
      - tourthecity-mysqldb
    ports:
      - "8090:8090"
    environment:
      - MYSQL_DATABASE_URL=jdbc:mysql://mysqldb:3306/tourthecitydb
      - MYSQL_DATABASE_USERNAME=root
      - MYSQL_DATABASE_PASSWORD=A4q9VOAFwXIAB2nO8U9ofjlbyyR9ysNzHWEI87zJfWct1ENhCS
