FROM openjdk:17
ADD target/*.jar app.jar
ENTRYPOINT ["java","-jar","app.jar"]

#VOLUME /tmp
#ADD target/your-application.jar app.jar
#ENTRYPOINT ["java", "-jar", "/app.jar"]
#FROM openjdk:17

#WORKDIR /app
#
#COPY target/tourthecity.jar app.jar
#
#ENTRYPOINT ["java", "-jar", "app.jar"]

